### ISSUE TITLE
Support update payloads for arm64-usr

### ISSUE THREAD

**Issue by dongsupark** [kinvolk/nebraska#112]
At the moment, Nebraska simply assumes that every update payload is for amd64-usr.
So `amd64-usr` is hard-coded in places like https://github.com/kinvolk/nebraska/blob/16e843900344bee0c3ac43880457ab6afff85181/pkg/syncer/syncer.go#L242.

Also the `Packages` struct does not have any field about architecture. It has only `Version`:
https://github.com/kinvolk/nebraska/blob/16e843900344bee0c3ac43880457ab6afff85181/pkg/api/packages.go#L35
As a result, uploading multiple update payloads for the same version, one for amd and the other for arm, will simply fail, because the server already has the payload for the same version. `upload_package` script will simply fail like `Payload with version 2345.99.0 already present. Skipping upload...`.
To fix that, we probably need to add a new DB field `Arch` to `Package`.

We should figure out how to support both amd64-usr and arm64-usr.

**Comment by dongsupark** [comment]
Updated the description to mention that we need to add `Arch` field to `Package`.

**Comment by joaquimrocha** [comment]
Hey Dongsu,
Just letting you know this is in my radar and it's an important enhancement.
I will check with @krnowak next week about this issue so we can fix it ASAP. Thanks for reporting.
