### ISSUE TITLE
Add a no-auth/dev mode or bring the db auth back

### ISSUE THREAD

**Issue by krnowak** [kinvolk/nebraska#113]
This is to make it easy to test stuff in Nebraska. Or to easily setup some CI. Or to skip the use of Internet for testing a local instance of Nebraska.

Either add something like `-no-auth` flag or bring back the db auth back. The db membership system is currently quite limited (user can belong only to one team, app can be maintained by members of only one team). But maybe is enough for testing.

**Comment by krnowak** [comment]
Partially addressed by #116.

**Comment by joaquimrocha** [comment]
I'll close this down as the main point was to bypass real auth when testing locally (which #116 does). Thanks.
