### ISSUE TITLE
Fix instances backend pagination

### ISSUE THREAD

**Issue by joaquimrocha** [kinvolk/nebraska#122]
The API method that fetches the instances from the DB supports pagination but it's incompatible with the needed use-case for two main reasons:

1. There is no way of getting the total count of the instances when they have been filtered (by version and/or status). So we cannot display e.g. "200/1000" in the instance view unless we retrieve all the instances before (which defeats the purpose of pagination).

2. The pagination is happening [before](https://github.com/kinvolk/nebraska/blob/65c6f69db6e6df87bb2cc848439e489893726c17/pkg/api/instances.go#L269) the filters are applied, which means that if we happen to request a page that has no instances matching the filters, nothing is returned.

In order to fix this and make it useful, we should return the maximum number of instances + the number of filtered instances + the actual filtered and paginated instances in the result.

**Comment by ashu8912** [comment]
@joaquimrocha this is fixed and can be closed now

**Comment by joaquimrocha** [comment]
Thanks @ashu8912 .
