### ISSUE TITLE
Optimize instances queries

### ISSUE THREAD

**Issue by joaquimrocha** [kinvolk/nebraska#123]
Due to #122 , we cannot use the pagination in an effective way, and thus the instances page become heavier with the number of instances.

This issue is about optimizing that view once the mentioned issue is fixed.

**Comment by ashu8912** [comment]
@joaquimrocha this is fixed

**Comment by ashu8912** [comment]
ref #173

**Comment by joaquimrocha** [comment]
Thanks. Closed.
