### ISSUE TITLE
Show Nebraska version in the UI

### ISSUE THREAD

**Issue by joaquimrocha** [kinvolk/nebraska#144]
We should be able to see Nebraska's version in the UI (or accessible through the browser anyway) as it may be useful when deploying new versions and reporting bugs.

**Comment by ashu8912** [comment]
hey @joaquimrocha where are we planning to show the version in the ui also is there a property in code that stores current version

**Comment by joaquimrocha** [comment]
This should be sent together with the configuration map we send from the backend (see the /config API endpoint).
