### ISSUE TITLE
Add Js linter & commit hooks

### ISSUE THREAD

**Issue by joaquimrocha** [kinvolk/nebraska#149]
We should add a Js linter (locally when building, and in the CI), and also a commit hook (I have a half finished one for checking the commit messages).

Details TBD.

**Comment by ashu8912** [comment]
yes also a precommit-hook will be helpful that runs linter and prettier config before each commit

**Comment by ashu8912** [comment]
@joaquimrocha whats the status for the commit hook

**Comment by joaquimrocha** [comment]
We don't have any specific hooks but we do have the linter, so let's close this and maybe look into the hook later.
