### ISSUE TITLE
Allow to see instance's history when the list is filtered

### ISSUE THREAD

**Issue by joaquimrocha** [kinvolk/nebraska#150]
When in the instances view, if one filters the instances (e.g. to see only the ones with errors), it is impossible to open their history (clicking the IP).

Steps to reproduce:
1. Go to a group's instance view and filter the instances by status (e.g. choose the Error).
2. Click the IP address, to open the instance's quick history view.
3. Verify that the quick history is not opened, instead, the filter is reset (I think this is the cause of why the history is not shown).

Acceptance criteria:
1. Follow the steps above until the second one.
2. Verify the history view is opened and the filter is not reset.

**Comment by ashu8912** [comment]
@joaquimrocha this was merged in master and thus this issue can be closed

**Comment by joaquimrocha** [comment]
Fixed in version 0.2.5.
