### ISSUE TITLE
Remove moment.js

### ISSUE THREAD

**Issue by ashu8912** [kinvolk/nebraska#151]
momentjs has its all functions as member function. So you have to import all functions even you need only some function. Once you create a instance, all function are included.
and on the other side date-fns is divided by function level. So you can import and use only what you need and this removes a lot of unused and unnecessary code.

**Comment by ashu8912** [comment]
ref #37

**Comment by joaquimrocha** [comment]
Maybe we can even use standard date functions nowadays (instead of another dependency)?

**Comment by ashu8912** [comment]
yes @joaquimrocha date-fns supports only javascript date APIS so i think it will be better to rather use the Date Api directly as we dont have much use of moment will see if it requires to create custom method will create that as well
