### ISSUE TITLE
Nebraska keeps too many connections to the DB

### ISSUE THREAD

**Issue by iaguis** [kinvolk/nebraska#182]
I'm seeing a lot of connections to the DB so it seems Nebraska is leaking connections.

We should:

* Use [SetMaxIdleConns](https://golang.org/pkg/database/sql/#DB.SetMaxIdleConns) and [SetMaxOpenConns](https://golang.org/pkg/database/sql/#DB.SetMaxOpenConns) because the default is unlimited.
* Check we're not holding on to connections after doing DB operations.

**Comment by ashu8912** [comment]
@iaguis i think we have a fix to this problem now @joaquimrocha this can be closed

**Comment by joaquimrocha** [comment]
Yup. Released in 2.0.7.
