### ISSUE TITLE
Missing a 404 page on the frontend

### ISSUE THREAD

**Issue by ashu8912** [kinvolk/nebraska#183]
Right now if we visit a untracked route on page we see empty body of our page because of which the user now can not navigate to the home page through page.
 A 404 page will help users navigate back to the home page when they have visited a wrong route.

**Comment by joaquimrocha** [comment]
Let's hold on this until we have the new design revamp.

**Comment by joaquimrocha** [comment]
We have design for the 404 page now, so we should implement it:
![image](https://user-images.githubusercontent.com/1029635/147224148-57f391b1-c907-48d0-9604-a46731ac61e2.png)

**Comment by yolossn** [comment]
Fixed by https://github.com/kinvolk/nebraska/pull/597
