### ISSUE TITLE
Optimize getting apps

### ISSUE THREAD

**Issue by joaquimrocha** [kinvolk/nebraska#184]
The home view (apps) seems to take quite some time under certain setups/DB when it tries to get the apps. So we need to investigate this issue and eventually optimize what's being done in those functions/queries.

**Comment by ashu8912** [comment]
ref  #193

**Comment by ashu8912** [comment]
@joaquimrocha this can be closed now

**Comment by joaquimrocha** [comment]
This is fixed by the patches that fixed #182 as well.
