### ISSUE TITLE
Create release process

### ISSUE THREAD

**Issue by krnowak** [kinvolk/nebraska#185]
We added a version of nebraska as a string to the code, so now when doing a release, we will need to remember to bump it. From my experience this thing is almost always forgotten about. To avoid that, we need a document about the release process and maybe some scripts to automate some parts of the process.

**Comment by ashu8912** [comment]
ref #192

**Comment by ashu8912** [comment]
@joaquimrocha this can be closed now

**Comment by joaquimrocha** [comment]
:+1:
