### ISSUE TITLE
public update server 404

### ISSUE THREAD

**Issue by anole1980** [kinvolk/nebraska#186]
The public update site: `https://public.update.flatcar-linux.net/v1/update/`, is now responsing 404. I'm not sure if this is the right place for this issue, but I have nowhere to go. 
Someone check it up pls!

**Comment by iaguis** [comment]
Hi!

That endpoint expects a POST request with a specific XML payload, not a GET request.

If you do a post you get a `200 OK` response:

```
$ curl -IL -XPOST https://public.update.flatcar-linux.net/v1/update/
HTTP/2 307
date: Fri, 17 Apr 2020 12:58:49 GMT
content-length: 0
location: /v1/update

HTTP/2 200
date: Fri, 17 Apr 2020 12:58:49 GMT
content-type: text/xml
content-length: 0
```

Do you have a specific problem updating?

**Comment by anole1980** [comment]
It's pretty weired, I excute your command in my home, I got this:

```
$ curl -IL -XPOST https://public.update.flatcar-linux.net/v1/update/
HTTP/2 504 
server: awselb/2.0
date: Fri, 17 Apr 2020 15:18:45 GMT
content-type: text/html
content-length: 148
```
And, I run it on a remote VM which located in AU, I got this:
```
# curl -IL -XPOST https://public.update.flatcar-linux.net/v1/update/
HTTP/1.1 504 Gateway Time-out
Server: awselb/2.0
Date: Fri, 17 Apr 2020 15:19:59 GMT
Content-Type: text/html
Content-Length: 148
Connection: keep-alive

```
But, after a few minutes, I rerun the same command, the correct respond came up:

```
$ curl -IL -XPOST https://public.update.flatcar-linux.net/v1/update/
HTTP/2 307 
date: Fri, 17 Apr 2020 15:22:47 GMT
content-length: 0
location: /v1/update

HTTP/2 200 
date: Fri, 17 Apr 2020 15:22:47 GMT
content-type: text/xml
content-length: 0
```
So, I'm assuming that this could be a server overload issue. If I'm right, does this mean your server needs a scale up or some performance tweak?

**Comment by iaguis** [comment]
Thanks for reporting!

I see in our monitoring that the update service was down from ~14:30 UTC until ~15:20 UTC, which seems to explain the behavior you were seeing. We're working to improve its reliability.

About the download speed issue, this is a separate problem since payloads are not co-located with the update service, they are distributed in several caching servers around the world. May I ask where you're located?

**Comment by anole1980** [comment]
I'm in China. So It maybe out of your reach.

**Comment by joaquimrocha** [comment]
Closing since there are no new details and the outing seems to have explained the 404.
