### ISSUE TITLE
Serve frontend build for all unhandled routes at backend

### ISSUE THREAD

**Issue by ashu8912** [kinvolk/nebraska#188]
### Current Behaviour
We only serve our frontend build when the server is requested for "/" route, this is fine as when we go to the home page and refresh,, the server serves the correct files and then every route we visit is handled by frontend routing.

### Problem
But the problem now comes when we visit some frontend route and press refresh button,, now our app asks server please serve the following routes file but the server doesn't have such a route as that route was created by frontend and backend doesn't have any idea about it and thus server sends a 404 error. 

### Solution
Our backend should serve our frontend for all unmatched URLs and when we do that our server serves the build and now our frontend routing kicks in.

**Comment by ashu8912** [comment]
@joaquimrocha this can be closed now

**Comment by joaquimrocha** [comment]
:+1:
