### ISSUE TITLE
Ban caching of index.html

### ISSUE THREAD

**Issue by krnowak** [kinvolk/nebraska#20]
Applicable after #16 is merged.

Currently browsers can cache index.html and that breaks the authentication a bit - if the page is cached and we are not authenticated we are likely to end up with a blank page, because browser renders the cached index.html and fetches just some css files from rollerd. The browser won't get them but it also won't redirect the user to the github.

**Comment by joaquimrocha** [comment]
> Avoiding caching would be a way to get around the glitch, but the better change probably would be to teach the frontend JS code to ask the user to re-authenticate and redirect to login when requests to the API fail due to permission errors.

Yup. This is the way to go.

**Comment by joaquimrocha** [comment]
I don't think this is happening anymore, so I am closing it.
