### ISSUE TITLE
Don't show the duration links if there is nothing to be shown

### ISSUE THREAD

**Issue by joaquimrocha** [kinvolk/nebraska#202]
I have noticed that we show the duration links in the group extended view even if they don't have any instances to report:

![Screenshot from 2020-05-06 15-15-38](https://user-images.githubusercontent.com/1029635/81182082-a6df7d00-8fad-11ea-86d9-991dadb85102.png)

Ideally we disable those links if there is no duration for the user to see.
The strategy for doing this should be:

1. get the instances/count for the default duration (1 day in this case);
2. if nothing is reported, set the link's state to disabled and repeat 1 but for the longer duration after the current one.

This should allow the user to get directly into a duration that is useful.
If this requires a long time when no instances for 30d are there, then we can take a lazy approach:

1. get the instances/count for the current duration (default 1 day in this case);
2. if nothing is returned, disable the current duration link and the ones that are less than it.

This means that if the user gets to the view (1 day) and there are no instances, then 1day and 1hour durations are disabled. If they then click on 30 days and there is nothing, 30 day and less gets disabled (i.e. all the links get disabled).

**Comment by ashu8912** [comment]
@joaquimrocha this can be closed now as we have the changes in master now
