### ISSUE TITLE
RFE: OIDC login for support

### ISSUE THREAD

**Issue by vbatts** [kinvolk/nebraska#220]
A feature for users to have available logging in for support assistance.
This would rely on services that are not finished yet, but would make for a smooth user experience for those managing an update-service.

**Current situation**
We can use either the Github auth or a noop (for development).

**Impact**
This means that users who want authentication but don't use Github don't have a good alternative.

**Ideal future situation**
There is ideally a generic way to authenticate with any provider who offers OIDC.

**Implementation options**
Implement the use of generic OIDC. The tricky part should be on how to determine which users can authenticate, and how do they get their roles (`view` and `admin`).

**Comment by alloveras** [comment]
Hey @vbatts,
I'd be interested in moving this forward. However, I am not entirely sure about what you mean by:

> This would rely on services that are not finished yet

Does this mean that the development of this feature is blocked by some other features that need to land first? 

Thanks 😄

**Comment by vbatts** [comment]
@alloveras I don't think it is blocking the work on any OIDC feature here. I'm referring to standing up a kinvolk managed accounts, so users can identify their nebraska instance to kinvolk.

**Comment by alloveras** [comment]
Thanks for clarifying that @vbatts.

I haven't had much time to look deeper into the current authentication model. I will have a deeper look and try to write an implementation proposal. 

Is that how you guys expect people to propose new changes or you prefer people to send PRs directly?

**Comment by vbatts** [comment]
PRs can be easier, but when it is super involved, like a refactor or relies
on other features, then PRs can be painful. That's when it's fruitful to
propose and discuss first.
Something like this could be incremental.
