### ISSUE TITLE
Rework flatcar action table to enable easy upserting

### ISSUE THREAD

**Issue by krnowak** [kinvolk/nebraska#231]
(Some of the ideas and realizations occured to me while writing this issue.)

Currently flatcar_action table looks like:

```sql
create table flatcar_action (
	id uuid primary key default uuid_generate_v4(),
	…
	package_id uuid not null references package (id) on delete cascade
);
```

Our code assumes that every flatcar package in our database has zero or one entry in `flatcar_action` table. So updating the package may involve updating a row in flatcar_action. Currently our code tries to get the action for the package and if there are no such actions it inserts a new one; if there is an action already in the database it updates it. The code is here: https://github.com/kinvolk/nebraska/blob/8f2a165389814224aae1ce6d7560c6cc7486cf99/pkg/api/packages.go#L191-L219

(The code is a bit convoluted and buggy, which had slipped in my review.)

It could be solved in two ways:

1. make `package_id` row in `flatcar_action` unique and replace the code above with:

```go
query, _, err = goqu.Insert("flatcar_action").
	Cols("package_id", "sha256").
	Vals(goqu.Vals{pkg.ID, pkg.FlatcarAction.Sha256}).
	OnConflict(goqu.DoUpdate("package_id", goqu.Record{"sha256": pkg.FlatcarAction.Sha256})).
	Returning(goqu.T("flatcar_action").All()).
	ToSQL()
```

2. replace the code above with:

```go
if pkg.FlatcarAction.ID == "" {
	pkg.FlatcarAction.ID = uuid.New().String()
}
query, _, err = goqu.Insert("flatcar_action").
	Cols("id", "package_id", "sha256").
	Vals(goqu.Vals{pkg.FlatcarAction.ID, pkg.ID, pkg.FlatcarAction.Sha256}).
	OnConflict(goqu.DoUpdate("id", goqu.Record{"sha256": pkg.FlatcarAction.Sha256, "package_id": pkg.FlatcarAction.Sha256})).
	Returning(goqu.T("flatcar_action").All()).
	ToSQL()
```

**Comment by ashu8912** [comment]
@krnowak thanks for the detailed explaination of the correct way. I went with second way because its easy to understand and doesn't require change outside the file.
