### ISSUE TITLE
More forgiving X-Forwarded-For handling

### ISSUE THREAD

**Issue by mleklund** [kinvolk/nebraska#324]
**Current situation**
I am currently using an oauth2 proxy that does not properly form X-Forwarded-For headers, using comma separators and not comma plus space separators. It is not the first time I have run access proxies that behave this way. 

**Impact**
The wrong host ip shows up in Nebraska. 

**Ideal future situation**
Be forgiving of noncompliant headers. 

**Implementation options**
Split the XFF header by commas then trim any spaces.  

**Additional information**
I plan to open a ticket with the proxy source base as well, just thought the simple fix could save someone some time down the road.

**Comment by joaquimrocha** [comment]
Hi @mleklund , can you share (maybe a screenshot) of what the IPs look like under your setup?
If it helps before we get to fix that issue, you can rename instances since version 2.3.0 (just in case you were using the IPs to identify instances).

**Comment by mleklund** [comment]
If I route the request directly from my nginx ingress, it works properly, if I route from my oauth2 proxy it shows the ip address of the proxy pod. From the (envoy based) proxy's logs:

```
{"level":"info","service":"envoy","upstream-cluster":"policy-1e04ff8a87f1793d","method":"POST","authority":"nebraska.ops.svc.cluster.local","path":"/v1/update/","user-agent":"","referer":"","forwarded-for":"10.10.50.42,10.244.211.237","request-id":"a732dcc6-4c41-4043-8ea0-8d17d052a3c0","duration":13.595065,"size":0,"response-code":307,"response-code-details":"via_upstream","time":"2021-01-19T19:36:05Z","message":"http-request"}
```

I added some debug to get the value of ips from nebraska:

```
{"_t":"2021-01-19T22:53:51+0000"", "_p":"1", "_l":"DBG", "_n":"nebraska", "_m":"header debug", "header":"X-Forwarded-For", "value":"10.10.50.42,10.244.211.237"}
{"_t":"2021-01-19T22:53:51+0000", "_p":"1", "_l":"DBG", "_n":"nebraska", "_m":"ip debug", "_":"10.10.50.42,10.244.211.237"}
```

And here is a patch for my fix, though I am certainly willing to open a pull request, I am not a go programmer, so there may be a better way:

```
diff --git a/cmd/nebraska/controller.go b/cmd/nebraska/controller.go
index 3ac59d6..d5b1d92 100644
--- a/cmd/nebraska/controller.go
+++ b/cmd/nebraska/controller.go
@@ -889,7 +889,10 @@ func (ctl *controller) processOmahaRequest(c *gin.Context) {
 //

 func getRequestIP(r *http.Request) string {
-       ips := strings.Split(r.Header.Get("X-FORWARDED-FOR"), ", ")
+       ips := strings.Split(r.Header.Get("X-FORWARDED-FOR"), ",")
+       for i := range ips {
+               ips[i] = strings.TrimSpace(ips[i])
+       }
        if ips[0] != "" && net.ParseIP(ips[0]) != nil {
                return ips[0]
        }
```

![Before Fix](https://user-images.githubusercontent.com/2934690/105216497-416df500-5b18-11eb-90b1-80314a44c8ad.png)
![After fix](https://user-images.githubusercontent.com/2934690/105216499-42068b80-5b18-11eb-87e9-257cf2d94b36.png)

**Comment by mleklund** [comment]
I want to note that when I took the screenshots the envoy proxy had been rebooted so it changed ip addresses slightly from when the log files were taken.  10.244.211.237 => 10.244.211.239

**Comment by joaquimrocha** [comment]
@mleklund , Thanks for the further clarification and patch!
AFAIU, the logic still chooses the first IP in the list, so from the logs you've pasted, this means you'd see `10.10.50.42`. If somehow in a proxied connection the machine's IP always comes last, we can change the logic to do that, but I am a bit puzzled as to why your screenshots show the 2 different IPs while keeping the same 1st-IP logic.

**Comment by mleklund** [comment]
Here is the original nebraska code:

```
func getRequestIP(r *http.Request) string {
	ips := strings.Split(r.Header.Get("X-FORWARDED-FOR"), ", ")
	if ips[0] != "" && net.ParseIP(ips[0]) != nil {
		return ips[0]
	}
	ip, _, _ := net.SplitHostPort(r.RemoteAddr)
	return ip
}
```

In my case the XFF is set to `10.10.50.42,10.244.211.237`, the code does a split on ", " (comman and space) per RFC, since my XFF from envoy does not have a space it does not split setting `ips[0] = "10.10.50.42,10.244.211.237"`.  `ips[0]` does not equal empty string, and net.ParseIP returns a nil because it cannot be parsed properly.  `ip` is then set to the calling ip `10.244.211.237`. The screenshot reads `10.244.211.239` because it was captured on a subsequent run that had redeployed the envoy proxy, I am sure it was `10.244.211.237` at the time the logs above were captured.

My patched code looks like this:

```
func getRequestIP(r *http.Request) string {
	ips := strings.Split(r.Header.Get("X-FORWARDED-FOR"), ",")
        for i := range ips {
                ips[i] = strings.TrimSpace(ips[i])
        }
	if ips[0] != "" && net.ParseIP(ips[0]) != nil {
		return ips[0]
	}
	ip, _, _ := net.SplitHostPort(r.RemoteAddr)
	return ip
}
```

Now with my patch, I split the XFF on only comma, and then trim any spaces from the split array.  This allows `ip[0]` to be set to `10.10.50.42`.  I understand the envoy is not sending an RFC compliant XFF header here, and I intend to open an issue with them as soon as I understand what is happening there.  I have confirmed my nginx ingress is passing a proper XFF header to envoy, and that envoy is adding it's own IP address to the list, but that the header envoy is sending out is not `comma + space` delimited.

**Comment by mleklund** [comment]
After some research xff header falls under [rfc2616 section 4.2](https://tools.ietf.org/html/rfc2616#section-4.2), which does only require a comma.  However it is a defacto standard implemented by many as comma+space.  As I said, I am willing to provide the above as a pull request, though there may be a more efficient way to do what I am doing in go.

**Comment by joaquimrocha** [comment]
@mleklund , No worries. This has been very helpful. We'll pick it up from here.
My previous questions were just about learning whether getting and showing always the first IP was fine.
