### ISSUE TITLE
Use postgresql driver other than gopkg.in/dat.v1

### ISSUE THREAD

**Issue by dongsupark** [kinvolk/nebraska#34]
At the moment Nebraska relies heavily on [gopkg.in/dat.v1](https://github.com/mgutz/dat) for communicating with its Postgresql database. That's inherited from the coreroller era.

However, both dat and [logxi](https://github.com/mgutz/logxi), its logging library, are not maintained since many years. So it's not possible to migrate dependent projects to Go modules, and it's unlikely that any upstream PRs against the projects could be merged.

We need to think about an option to replace dat with a Postgres driver which is widely used and actively developed, for example:
* https://github.com/jackc/pgx
* https://github.com/lib/pq

**Comment by joaquimrocha** [comment]
The driver has been replaced by `pq` and `goku` and merged to master. Closing this issue.
