### ISSUE TITLE
React error when expanding the instance status in the instance status list

### ISSUE THREAD

**Issue by pothos** [kinvolk/nebraska#343]
**Description**

In the view `apps/123/groups/123/instances?period=1d&status=Error` expanding an instance with the `↓` expander results in a white screen and throws a react error to the JS console.

https://reactjs.org/docs/error-decoder.html/?invariant=31&args says I hit `Objects are not valid as a React child (found: [missing argument]). If you meant to render a collection of children, use an array instead.`

**Impact**

Can't see the error description unless the individual instance detail view is opened.

**Comment by ashu8912** [comment]
thanks @pothos for reporting this
