### ISSUE TITLE
Allow to delete instances

### ISSUE THREAD

**Issue by joaquimrocha** [kinvolk/nebraska#352]
**Current situation**
Users cannot delete instances forever which is something perhaps desirable when retiring a machine complete.
Maybe hiding (instead of deleting) would also work, but that use-case may already be covered if we have a good search capability (#351).

**Impact**
Users have to keep seeing the instances that may have been test ones or may have been retired, which will make the use of the instances list more complicated.

**Ideal future situation**
Users can easily select a number of instances and choose to remove them.

**Implementation options**
We could allow to remove them from the instances list view with an edit mode for selecting multiple (or all) instances and delete them.

**Comment by joaquimrocha** [comment]
Related #148

**Comment by joaquimrocha** [comment]
I am closing this in favor of #148 as it's less destructive.

**Comment by pothos** [comment]
Deleting could maybe serve as last resort if the instance state in the DB is causing problems and the instance is somehow stuck. This should not be the case after the last fixes in this area, but it may be useful to workaround future bugs.

**Comment by joaquimrocha** [comment]
My reasoning is that I don't want to support a destructive feature until we realize whether that's a good idea.
At an extreme we could have a way to reset the instance's state directly, but I'd prefer if we can prevent any issues with the state from the beginning.

**Comment by echo-devnull** [comment]
Not to re-open this ticket, but I think there is a use case for managing instances?

We have multiple clusters, adding and removing flatcar nodes hourly by the 10's.
Cluster nodes are also replaced on a regular basis. 

Is there a good way to manage replaced and removed instances?

**Comment by jescarri** [comment]
Thanks for making Nebraska, it is  a great tool.

I think there needs to be a way to auto-remove or hide instances that are no longer reporting to the update server.

In the kubernetes use case we have k8s clusters running flatcar and we use nebraska + flatcar-upgrade operator to roll new versions in a controlled maner.

However we replace worker nodes from time to time when a cluster scales up/down we end up with a lot of old instances in the database.

Thanks!
