### ISSUE TITLE
Reduce size of bundle / Add CRA-rewired

### ISSUE THREAD

**Issue by joaquimrocha** [kinvolk/nebraska#37]
From Webpack:

> WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
> This can impact web performance.
> Assets: 
>   main.js (1.46 MiB)
> 
> WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
> Entrypoints:
>   main (1.46 MiB)
>       main.js
> 
> 
> WARNING in webpack performance recommendations: 
> You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
> For more info visit https://webpack.js.org/guides/code-splitting/
> 

So we should fix it, and probably a good way to do it is to integrate create-react-app (rewired) to the project.

**Comment by ashu8912** [comment]
@joaquimrocha this can be closed now

**Comment by joaquimrocha** [comment]
:+1:
