### ISSUE TITLE
GROUP is overwritten after upgrade and reboot on update.conf

### ISSUE THREAD

**Issue by JesusRo** [kinvolk/nebraska#384]
## Description

Custom `GROUP` configured on /etc/flatcar/update.conf is reset to `stable` (the channel of the group) after an upgrade.

## Impact

When vms are updated, reconfiguration of the group on  /etc/flatcar/update.conf is needed

## Environment and steps to reproduce

1. **Set-up**: 
VMs deployed on Openstack
Nebraska instance deployed via helm chart
2. **Task**: 
Updating node
3. **Action(s)**: 
Create group on Nebraska:
```
          "name":"My Stable",
          "track":"My dev stable",
          "description":"My dev stable Cluster vms",
          "policy_updates_enabled":true,
          "policy_safe_mode":true,
          "policy_max_updates_per_period":999999,
          "policy_period_interval":"1 hours",
          "policy_update_timeout":"60 minutes",
          "channel_id":"e06064ad-4414-4904-9a6e-fd465593d1b2",
          "policy_timezone":"Europe/Berlin",
          "application_id":"e96281a6-d1af-4bde-9a0a-97b76e56dc57"
```
Logging into node and update /etc/flatcar/update.conf
```
        GROUP=68845645-6854-5615-1658-918957649868
        SERVER=https://mylocal-nebraska.local/v1/update/
        MACHINE_ALIAS=flatcar-test-1.local
```
Run:
 - systemctl restart update-engine
 - /usr/bin/update_engine_client -reset-status
 - /usr/bin/update_engine_client -check_for_update
when `/usr/bin/update_engine_client -status` says we are ready for reboot, reboot the node

4. **Error**: 
Logging back to the node, /etc/flatcar/update.conf has `GROUP` changed to stable as below
```
        GROUP=stable
        SERVER=https://mylocal-nebraska.local/v1/update/
        MACHINE_ALIAS=flatcar-test-1.local
```
## Expected behavior
Logging back to the node, /etc/flatcar/update.conf should have been not modified
```
        GROUP=68845645-6854-5615-1658-918957649868
        SERVER=https://mylocal-nebraska.local/v1/update/
        MACHINE_ALIAS=flatcar-test-1.local
```

## Additional information

Followed https://kinvolk.io/docs/nebraska/latest/managing-updates/#existing-machines for setting up updates.conf file

**Comment by pothos** [comment]
You have some software running that does this, not related to Nebraska. Did you trigger Ignition to set up this file or even cloud init which is more tricky because it will run at each boot. I recommend you to use Ignition user data (the JSON format transpiled from Container Linux Config).

**Comment by JesusRo** [comment]
I'm currently using cloud init but there is nothing there.
Actually I just test it again, and realized group was updated and also `REBOOT_STRATEGY=off` was added
Anyhow, agree this is actually not related with Nebraska itself, I will open discussion on flatcar, maybe it's related with the update_engine 

Thanks!

**Comment by JesusRo** [comment]
For future ref: https://github.com/kinvolk/Flatcar/issues/413
