### ISSUE TITLE
Blank page on chart version 0.1.4

### ISSUE THREAD

**Issue by JesusRo** [kinvolk/nebraska#389]
## Description

Nebraska UI gives blank page

## Impact

Not able to use UI

## Environment and steps to reproduce

1. **Set-up**: 
Deployed via helm chart 0.1.4
(image quay.io/flatcar/nebraska:2.3.5)

## Expected behavior

Nebraska UI is working

## Additional information

I noticed notes on documentation to clean up cache as mentioned on https://kinvolk.io/docs/nebraska/2.3/authorization/#troubleshooting

However it did not work, using private mode on firefox and chrome with full clear of any cached data on browser.
It shows blank page and bellow errors on console
```
SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
    Y Header.tsx:135
    Ja 2.d3e51762.chunk.js:2
    Ac 2.d3e51762.chunk.js:2
    vu 2.d3e51762.chunk.js:2
    bu 2.d3e51762.chunk.js:2
    cu 2.d3e51762.chunk.js:2
    nu 2.d3e51762.chunk.js:2
    Hu 2.d3e51762.chunk.js:2
    u 2.d3e51762.chunk.js:2
    lu 2.d3e51762.chunk.js:2
    $u 2.d3e51762.chunk.js:2
    render 2.d3e51762.chunk.js:2
    746 index.tsx:6
    a (index):1
    t (index):1
    r (index):1
    <anonymous> main.78ecd69f.chunk.js:1
2.d3e51762.chunk.js:2:783178
Uncaught SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
    Y Header.tsx:135
    Ja 2.d3e51762.chunk.js:2
    Ac 2.d3e51762.chunk.js:2
    vu 2.d3e51762.chunk.js:2
    bu 2.d3e51762.chunk.js:2
    cu 2.d3e51762.chunk.js:2
    nu 2.d3e51762.chunk.js:2
    Hu 2.d3e51762.chunk.js:2
    u 2.d3e51762.chunk.js:2
    lu 2.d3e51762.chunk.js:2
    $u 2.d3e51762.chunk.js:2
    render 2.d3e51762.chunk.js:2
    746 index.tsx:6
    a (index):1
    t (index):1
    r (index):1
    <anonymous> main.78ecd69f.chunk.js:1
    ```

I did test to deploy v0.1.3 (image quay.io/flatcar/nebraska:2.3.4) and worked just fine after clearing cache.
Could you please help to diagnose this?

**Comment by ashu8912** [comment]
Hello @JesusRo thanks for reporting this, It is an issue on our end I have added a patch for this.
