### ISSUE TITLE
Add explanation widget to unclear form options

### ISSUE THREAD

**Issue by joaquimrocha** [kinvolk/nebraska#42]
When creating a group, users can choose options like: safe update, only office hours, etc.
These options, also having a helper text, are not very clear to users initially, so we should add a popup or dialog explaining that.

**Comment by ashu8912** [comment]
Yes A tooltip with the description will be good

**Comment by joaquimrocha** [comment]
I think this has been fixed or partially fixed by the recent theme changes. Closing this one.
