### ISSUE TITLE
Auto-complete list of packages when adding them to a channel

### ISSUE THREAD

**Issue by joaquimrocha** [kinvolk/nebraska#46]
Showing the full list of packages in a select popup when adding assigning a package to a channel is a bit overwhelming and may cause performance issues depending on the number of packages, so this view should be replaced by an auto-complete popup (like the timezones' picker).

Here is the issue:
![Screenshot from 2019-09-09 20-52-12](https://user-images.githubusercontent.com/1029635/64558494-44fa4500-d344-11e9-9719-0bc83156da79.png)

**Comment by ashu8912** [comment]
@joaquimrocha this is fixed

**Comment by joaquimrocha** [comment]
@ashu8912 Thanks. Closing.
