### ISSUE TITLE
Cannot assign channels to groups

### ISSUE THREAD

**Issue by joaquimrocha** [kinvolk/nebraska#476]
## Description

The channel seems to be ignored when assigning it to a group (by creating or editing the group).

## Impact

Nebraska's users cannot create a working (one that provides updates) group.

## Environment and steps to reproduce

1. Create a new application, and within it create a new group and a new channel.
2. Edit the group and choose the new channel. Save it.

## Expected behavior

The channel will show up as being assigned to the group.

## Actual behavior

The group will remain without the channel assigned to it.

## Additional information

Creating a group and choosing an existing channel at that very step will also not work.

**Comment by illume** [comment]
Closed via #491
