### ISSUE TITLE
Setup CI

### ISSUE THREAD

**Issue by krnowak** [kinvolk/nebraska#5]
We will likely want to setup travis as we already have a travis config file in the tree.

While doing it, the config file could be tweaked to not use the `coreroller/postgres`, but maybe use upstream postgres docker image. @schu ran the tests as follows:

```
docker run --rm --name coreroller-test-postgres -p 5432:5432 -d postgres
psql -h localhost -U postgres -c 'create database coreroller'
psql -h localhost -U postgres -c 'create database coreroller_tests'
go test -p 1 ./...
```

`coreroller/postgres` creates the database in its entrypoint:

```
    gosu postgres psql -c "CREATE DATABASE coreroller;"
    gosu postgres psql -c "ALTER DATABASE coreroller SET TIMEZONE = 'UTC';"

    gosu postgres psql -c "CREATE DATABASE coreroller_tests;"
    gosu postgres psql -c "ALTER DATABASE coreroller_tests SET TIMEZONE = 'UTC';"
```

**Comment by joaquimrocha** [comment]
This is done. We're using Github actions.
