### ISSUE TITLE
Allow to modify group from the extended view

### ISSUE THREAD

**Issue by joaquimrocha** [kinvolk/nebraska#51]
When in the group extended view, it should be possible to edit the group, just like in the group list.

**Comment by ashu8912** [comment]
Hey @joaquimrocha the above link doesn't open for me can you share a screenshot of the view

**Comment by joaquimrocha** [comment]
I mistakenly deleted a comment by @ashu8912 . In any case, the view I am referring to is after clicking on a group's name.

**Comment by ashu8912** [comment]
@joaquimrocha  this issue can be closed now
