### ISSUE TITLE
Following Auth0 guide results in 403s, misconfigured roles

### ISSUE THREAD

**Issue by goshlanguage** [kinvolk/nebraska#526]
# Summary
Hey team,

I've configured Nebraska to leverage SSO via Auth0 following the guide at:
https://kinvolk.io/docs/nebraska/latest/authorization/#preparing-auth0-as-an-oidc-provider-for-nebraska

Unfortunately, this results in getting 403s when calling the `apps/` and `api/` routes, and nebraska throws several errors.

There isn't specific information on passing the configuration back to the app in this configuration, so its possible that I've gotten something wrong and this is user error. If so, my apologies.

I'm happy to clarify the docs where possible but I have a few questions regarding this guide.

# Questions

## 1. Are there any non default grants necessary for this to work as expected? 

I imagine `implicit`, `authorization_code`, and `refresh_token` (the defaults) should suffice, but when I go through the auth flow, the following errors are generated by nebraska:

`Refresh token not found in session`: [oidcauth.go](https://github.com/kinvolk/nebraska/blob/1b9e39c8324717bc7a444f32ac6ed9c1bc49f8ee/backend/cmd/nebraska/auth/oidcauth.go#L339)
`Misconfigured Roles, Can't get access level from token`: [oidcauth.go](https://github.com/kinvolk/nebraska/blob/1b9e39c8324717bc7a444f32ac6ed9c1bc49f8ee/backend/cmd/nebraska/auth/oidcauth.go#L381)

I believe the refresh token part to be a misnomer caused by how the logic works, ie it is leveraging the `authorization_code` grant first, then a subsequent request is made with the `refresh_token` grant.

## 2. Are defined scopes required for this to work?

It seems like there are no defaults for the scopes configuration, and they aren't inherited from the provider in [oidcauth.go](https://github.com/kinvolk/nebraska/blob/1b9e39c8324717bc7a444f32ac6ed9c1bc49f8ee/backend/cmd/nebraska/auth/oidcauth.go#L73-L94)

Are these necessary? I've tried adding some of the scopes provided via the `/oauth/.well-known/openid-configuration` endpoint response, but often times, it results in the roles being omitted from the JWT token.

## 3. How should the roles be configured and passed to the app?

The JWT token returned in the auth flow has the following structure in its payload, expected from the instructions in the guide:

```
{
  "http://kinvolk.io/roles": [
    "admin",
    "viewer"
  ],
  ...
}
```

And the deployed application gets the following flags appended to the binary (by way of the helm chart):

```
            - '-auth-mode=oidc'
            - '-oidc-admin-roles=admin'
            - '-oidc-viewer-roles=viewer'
            - '-oidc-roles-path=http://kinvolk.io/roles'
```

Yet, the application specifies: `Misconfigured Roles, Can't get access level from token`.

Tracing through the application logic, it seems like this should be appropriately passed to the `Authenticator` through the `OIDCAuthConfig` through the `NewOIDCAuthenticator` factory ([oidcauth.go:119](https://github.com/kinvolk/nebraska/blob/1b9e39c8324717bc7a444f32ac6ed9c1bc49f8ee/backend/cmd/nebraska/auth/oidcauth.go#L119)) and then called by the middleware when authenticating a request ([controller.go:186-195](https://github.com/kinvolk/nebraska/blob/916dcec9cdfdd4b6454d2a18fbf62d6f6f74bab8/backend/cmd/nebraska/controller.go#L186-L195)). 

If I change the `oidc-roles-path` flag to the suggested default, ["roles"](https://github.com/kinvolk/nebraska/pull/372/files#diff-6363609fc1c4952e7ad115ad447ddddd82b8fdb175fa0e7d57dec71050759134R58), the error no longer persists, but the roles are not found still, and the 403s persist.

Thank you for any guidance on this matter.

**Comment by goshlanguage** [comment]
After a good deal of digging, I don't think the chosen library/function `gjson.Get` supports parsing the returned JSON in the way prescribed by the guide.

See this playground: https://go.dev/play/p/3F_j7l7b3zs

This playground emulates the `rolesFromTokens` function found [here](https://github.com/kinvolk/nebraska/blob/main/backend/cmd/nebraska/auth/oidcauth.go#L299-L317). When `gjson.Get` is passed the key `http://kinvolk.io/roles` prescribed in the guide, `gjson.Get` erroneously doesn't parse the key and value. 

Unfortunately, the role key needs to be in url format.

**Comment by goshlanguage** [comment]
It looks like any periods in the key should be escaped when passed to `nebraska`. 

This perhaps this can be simply called out in the documentation as an action item, though then the onus is on the operator to either understand this or potentially spend days troubleshooting why things aren't working as intended, as was the case for me.

**Comment by joaquimrocha** [comment]
@goshlanguage , thanks for looking into this.
@yolossn , can you take it from here?

**Comment by goshlanguage** [comment]
I'd be happy to put in a PR if it helps, however I don't know if it would be preferred to automatically escape periods from flags set for nebraska, or to have it called out in the documentation, or something else.

**Comment by yolossn** [comment]
Hey, @goshlanguage the `oidc-roles-path` argument expects a `JSON path`, and periods are used to define the nesting if any exists in the token. Since in this case there is no nesting and periods are part of the value itself it requires escaping. The help string for `oidc-roles-path` says `JSON path`. I agree adding a note section to Auth0 documentation makes sense.

**Comment by yolossn** [comment]
@joaquimrocha @goshlanguage I have created a PR adding a notes section to Auth0 configuration.
