### ISSUE TITLE
API endpoint `/api/apps/{appID}/packages` returns only 10 packages in 2.6

### ISSUE THREAD

**Issue by george-angel** [kinvolk/nebraska#583]
Hello, we have written a Terraform provider for Nebraska: https://github.com/utilitywarehouse/terraform-provider-nebraska which was written against Nebraska 2.4.

One of the data sources we have is "package" and in 2.4 we would call `/api/apps/%s/packages`: https://github.com/utilitywarehouse/terraform-provider-nebraska/blob/v0.1.2/nebraska/packages.go#L106 to get all packages. We would then match on version and arch to try and find the package to reference: https://github.com/utilitywarehouse/terraform-provider-nebraska/blob/v0.1.2/internal/provider/data_source_package.go#L150-L151.

Since updating to 2.6 - the API has somewhat changed, so now this is the call to get all packages: https://github.com/utilitywarehouse/terraform-provider-nebraska/blob/master/nebraska/packages.go#L75 using https://github.com/kinvolk/nebraska/blob/main/backend/api/spec.yaml#L734-L755 - as reference for available parameters. But this only returns 10 packages with the following versions:

```
3165.0.0
3165.0.0
3139.1.0
3139.1.0
3033.2.3
3033.2.3
2261.0.0
2247.99.0
2247.2.0
2191.5.0
```

More specifically this is creating a failure in our test deployment, where we have a "pinned" package data source defined as:

```
data "nebraska_package" "pinned" {
  version = "2905.2.1"
  arch    = "amd64"
}
```

Which provider says cannot be found - fair enough, I don't see it either calling the API manually.

```
curl 'http://localhost:8000/api/apps/e96281a6-d1af-4bde-9a0a-97b76e56dc57/packages?searchVersion=2905.2.1'
{"totalCount":0,"count":0,"packages":null}
```

We probably want to update this call to use https://github.com/kinvolk/nebraska/blob/main/backend/api/spec.yaml#L752-L755 - instead of trying to get *all* packages and then looping over to find one we want. But for now I would like to understand why Nebraska has only the 10 packages.

Thank you.

**Comment by yolossn** [comment]
Hey @george-angel,

Yes, there were changes in the API with the 2.6 release that introduced pagination to the API with the default `perpage` value as 10, you can use this param to get more packages but looping over to get the packages is recommended. We have added a `searchVersion` param which searches for packages with the similar version. I hope this answers your question.

**Comment by george-angel** [comment]
Hey @yolossn ! Thanks for the response, unfortunately neither of those two options seem to work for me here.

Here I'm trying to get all packages using a large `perpage` value as documented here: https://github.com/kinvolk/nebraska/blob/main/backend/api/spec.yaml#L746-L751

```
curl 'http://localhost:8000/api/apps/e96281a6-d1af-4bde-9a0a-97b76e56dc57/packages?page=1&perpage=100000' | jq -r '.packages[].version' | wc -l
16
```

Same call against Nebraska 2.4:

```
curl 'http://localhost:8000/api/apps/e96281a6-d1af-4bde-9a0a-97b76e56dc57/packages' | jq -r '.[].version' | wc -l
110
```

And using `searchVersion` against 2.6:

```
curl 'http://localhost:8000/api/apps/e96281a6-d1af-4bde-9a0a-97b76e56dc57/packages?searchVersion=2905.2.1'
{"totalCount":0,"count":0,"packages":null}
```

The bit I'm missing I think is how do all packages end up in Nebraska? Does my 2.4 production version have all these old packages because its been running for a while and it starts with "current" packages and accumulates new ones over it's lifetime?

Thank you.

**Comment by yolossn** [comment]
Hey @george-angel, 
If you are using Nebraska with `--enable-syncer=true` arg then by default the syncer at 1 hour frequency checks the `https://public.update.flatcar-linux.net/v1/update/` for new packages and creates them in your Nebraska instance. 

When you say
> Same call against Nebraska 2.4:

Do you mean that both the Nebraska 2.4 and 2.6 instances are pointing to the same Database ?

From my understanding of the provided information it can be the case that there are only 16 packages in the Nebraska 2.6 instance and the package with version 2905.2.1 doesn't exist. You can cross verify this from the Nebraska UI or else run the following SQL queries in the DB used by the Nebraska 2.6 instance.

To verify the package count returned by the API is correct:
```SQL
select count(*) from package where application_id='e96281a6-d1af-4bde-9a0a-97b76e56dc57';
```

To verify that if the package with version 2905.2.1 exists:
```SQL
select * from package where version like '%2905.2.1%';
```

**Comment by george-angel** [comment]
@yolossn thats correct, so the issue the way it was raised is incorrect. I'm correctly getting no response from the API - as the package doesn't exist.

We are running with syncer enabled: https://github.com/utilitywarehouse/flatcar-manifests/blob/master/base/nebraska/nebraska.yaml#L32-L38

To verify my understanding - when I spin up a new instance of Nebraska, with a fresh Postgres - it will pull all available packages from https://public.update.flatcar-linux.net/v1/update/. It will then check that location at the interval and add any *new* packages.

If I wanted to create a new channel and then pin that to an older version of Flatcar - I can only go back as far as when I first spun up my Nebraska instance.

We are using the following configuration for our provider in a development environment, where we test provider changes:

```
# pinned is a group pinned to a specific package version
data "nebraska_package" "pinned" {
  version = "2905.2.1"
  arch    = "amd64"
}

resource "nebraska_channel" "pinned" {
  name       = "pinned"
  arch       = "amd64"
  package_id = data.nebraska_package.pinned.id
}

resource "nebraska_group" "pinned" {
  name       = "pinned"
  track      = "pinned"
  channel_id = nebraska_channel.pinned.id
}
```

I wanted to update Postgres, but since there is no nice way to do that in Kubernetes. I decided to *delete* the Postgres instance, and re-initialise the setup. Erroneously thinking that I have all the data in Terraform config, and this won't matter.

I'm now coming to realisation that I can only reference packages that Nebraska has seen since it was started (more specifically Postgres that backs it).

Hopefully that makes sense, and I don't suppose there is a way to sync *all* Flatcar packages (including ones before the moment I start Nebraska with a fresh instance of Postgres).

Thank you very much.

**Comment by joaquimrocha** [comment]
> Hopefully that makes sense, and I don't suppose there is a way to sync all Flatcar packages (including ones before the moment I start Nebraska with a fresh instance of Postgres).

That's correct, by default syncing in Nebraska means setting the Flatcar known groups pointing to their latest packages in "public". It won't pull all the packages, just the ones that are currently pointed by the groups "upstream".
You can, of course, keep DB dumps or extract the data you need to seed on a fresh install. Or start with a script that picks the package data from `https://update.release.flatcar-linux.net/amd64-usr/` for example.

If I understand correctly, there's no issue related to the API, so I will close this one. If you have further questions, let us know.
