### ISSUE TITLE
Backend: Not able to access channels, packages or groups using the productId

### ISSUE THREAD

**Issue by yolossn** [kinvolk/nebraska#601]
Fetching an application using productID via API works whereas fetching the groups/channels/packages of an application using productID doesnt work.

![image](https://user-images.githubusercontent.com/22731013/164985003-6bfddfd4-c96b-43b2-93c8-ff5c7209cc27.png)

**Comment by joaquimrocha** [comment]
Hmm, that's right. We haven't updated it in the URL. This is not so drastic, since the user can navigate easily from the links, but it's less human-friendly.

**Comment by yolossn** [comment]
This issue is for the backend API, there are cases when we want to use the `Product ID` instead of the `App ID`. Fetching App using the `Product ID` works as expected but doesn't work for fetching other resources such as `channels`, `packages` etc
