### ISSUE TITLE
Frontend: Instances are only shown when the version filter is set

### ISSUE THREAD

**Issue by pothos** [kinvolk/nebraska#611]
## Description

The instance view shows no instances because the `version=` parameter has no value set which results in a HTTP 400 bad request being thrown: `parameter "version" in query has an error: empty value is not allowed`

## Environment and steps to reproduce

1. In the UI, go to Application → Group → Instances and see that no instances are shown unless a version filter is set

## Expected behavior

All instances are shown

**Comment by mkilchhofer** [comment]
I also have this issue on latest version (2.8.0)

**Comment by mkilchhofer** [comment]
For me it is fixed since 2.8.1:
<img width="1143" alt="grafik" src="https://user-images.githubusercontent.com/7290987/202199742-eb567702-b330-42dc-a5be-d145fc4bb735.png">
