### ISSUE TITLE
can't add LTS channel 

### ISSUE THREAD

**Issue by widovsky** [kinvolk/nebraska#637]
## Description

Probably our LTS channel has been removed in the past. We are trying to add the channel again, via Add new channel. But no new 3033.3x packages are uploaded. The Nebraska container runs with -enable-syncer=true -host-flatcar-packages=true -flatcar-packages-path=/var/flatpkg 
Stable and Beta channels get the packages, that's fine. But no packages for LTS.

## Impact

Not possible to to use the LTS Channel

## Environment and steps to reproduce

1. Manually remove LTS channel
2. Add LTS channel

## Expected behavior

To pick 3033.3x packages in the newly added LTS channel 

## Additional information

Please add any information here that does not fit the above format.

**Comment by pothos** [comment]
The channel should have the name `lts-2022`, can you check that? The group name and track can be chosen freely (normally you would want to use the default track `lts`) and you can have various groups pointing to that channel.

**Comment by widovsky** [comment]
Wauw, yes that did the trick. We had created a channel "lts" and "lts-2023". Thanks very much for your help.
